FROM node:22-alpine AS build

WORKDIR /app
COPY services/ui_web/package.json .
RUN npm install

COPY services/ui_web/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
